### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by songyule** [younth/react-swipes#14]
![image](https://user-images.githubusercontent.com/23656890/37748117-8b2219aa-2dbd-11e8-9760-563e745a137e.png)
进页面就报这个错。

**Comment by congzhaoyang** [comment]
同样的错误

**Comment by younth** [comment]
@songyule @congzhaoyang 你们的react版本是？

**Comment by congzhaoyang** [comment]
@younth 开始是16.1和16.2共存, 报了第一个错误. 点那个链接可以看到react官方的描述, 报错原因是react共存. 全部升级为16.2就不报第一个错误了. 

但是又报了另外的错误. 我忘记截图了.

**Comment by younth** [comment]
我刚试了 `16.2.0` 没有问题呢，麻烦把报错截图看看

**Comment by soraping** [comment]
试了下，react 16.4就会报错

**Comment by soraping** [comment]
我觉得应该是版本冲突导致的，我新起了一个项目跑了下可以运行，真实项目等下再试下换下版本
